### ISSUE TITLE
screen painter not working 

### ISSUE THREAD

**Issue by zaid13** [JaeHeee/FlutterWithMediaPipe#1]
when i open the app i cant see screen painter on any model .

**Comment by ranvirm** [comment]
Did you tap the button on the bottom right?

**Comment by zaid13** [comment]
yes I have tried it haunts for a second but can't see any screen painter  
I have also tried downloading from play store but still can't see anything beside the camera preview

**Comment by zaid13** [comment]
https://user-images.githubusercontent.com/47746351/136694816-64b46731-103d-4b9c-960a-c188cf282890.mp4

**Comment by BenPrzychodzki** [comment]
It seems to me that the reason for the error is the code that converts YUV format to RGB format.

**Comment by irshadshan** [comment]
Hi, This is working fine in iOS end, but while opened in android, when enabling detection on YUV420 image conversion method getting error, It showing, Out of range index value exception.

**Comment by irshadshan** [comment]
Hi, I got a solution for this, You can downgrade flutter version to 2.2.3, Then it will work perfectly...  Ref: https://issueexplorer.com/issue/flutter/flutter/89584

**Comment by JaeHeee** [comment]
@zaid13 

Thank you for your report.
I changed face detection painter. Please check screen painter.
